# Use a lightweight Nginx image
FROM nginx:alpine

# Set working directory to default Nginx HTML folder
WORKDIR /usr/share/nginx/html

# Copy your HTML file into the container
COPY . .

# Expose port 80 for the container
EXPOSE 80
